config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  #   # Redirests signing out users back to sign-in
  #   get "users", to: "devise/sessions#new"
  # end
  devise_for :users
  root "articles#index"
     resources :articles do
    resources :comments

    resources :likes, only: [:create, :destroy]
  end
  get '/user_report', to: 'user#report'#page where csv file is downloaded
  get '/sorted_user_report', to: 'user#sorted_report'
  get '/user_reports', to: 'user#reports'#report page
  get '/article_report', to: 'articles#report'
  resources :user
  get "users/deactivate/:id" ,as:"deactivate" , to: "user#deactivate"
  get '/user_profile', to: 'user#profile'
  get '/import', to: 'user#import'
  post '/import_users', to: 'user#import_users' do
    collection {post :import}
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  VALID_STATUSES = %w[public private]

  validates :status, inclusion: { in: VALID_STATUSES }

  # require 'csv'
  def self.to_csv3(options = {})
    CSV.generate( headers:true) do |csv|
      headers = ['Title','Description', "Comments" ,"Likes"]
      CSV.generate_line headers
      csv << headers
      all.each do |article|
          csv << [article.title,article.body,article.comments.length,article.likes.length]
      end
    end
  end

  def private?
    status == 'private'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  def index
    @article = Article.new
    if current_user.has_role? :admin
      @articles = Article.all.order('created_at DESC')
      @user = User.all
    else
      @articles=Article.where(user_id: current_user.id) .or(Article.where(status: :public)).order('created_at DESC')
    end
  end
  def show
    @article = Article.find(params[:id])
    @blog = @article
  end

  def create
    @article = Article.new(article_params)
    @article.user_id =current_user.id
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      @article.errors.full_messages(:body, "cannot be blank")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find_by(id: params[:id])
    if @article.destroy!
      flash[:success] ="deleted successful"
    else
       flash[:success] ="deleted Unsuccessful"
    end
    redirect_to root_path, status: :see_other
  end

  def report
    @article = Article.all
     respond_to do |format|
      format.html
      format.csv { send_data @article.to_csv3 }
      # format.xls { send_data @article.to_csv3(col_sep: "\t") }
      format.xlsx
     end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% if current_user.has_role? :admin %>
  <div class="form">
    <%= form_with model: article do |form| %>
      <div class="title">
<!--        <%#= form.label :title %><br>-->
        <%= form.text_field :title , value:current_user.first_name ,type: :hidden,placeholder: "Title"%>
        <% article.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div class="post">
      <a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %></a>
<!--        <%#= form.label :body %><br>-->
        <%= form.text_area :body ,placeholder: "Write something here"%><br>
        <% article.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
        <% end %>
       </div>
      <div class="status">
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private'], selected: 'public' %>
      </div>
      <div class="submit">
        <div class="image"><%=image_tag("Vector (4).png") %></div>
        <p> Live Video</p>
        <div class="image"><%=image_tag("Vector (5).png") %></div>
        <p> Photo/Video</p>
        <div class="image"><%=image_tag("Vector (6).png") %></div>
        <p> Feeling</p>
        <div class="button2">
          <%= form.submit "POST"%>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="form">
    <%= form_with model: article do |form| %>
      <div class="title">
  <!--      <%#= form.label :title %><br>-->
        <%= form.text_field :title , value:current_user.first_name ,type: :hidden,placeholder: "Title"%>
        <% article.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div class="post">
      <a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %></a>
<!--        <%#= form.label :body %><br>-->
        <%= form.text_area :body ,placeholder: "Write something here"%><br>
        <% article.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div class="status">
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private'], selected: 'public' %>
      </div>
      <div class="submit">
        <div class="image"><%=image_tag("Vector (4).png") %></div>
        <p> Live Video</p>
        <div class="image"><%=image_tag("Vector (5).png") %></div>
        <p> Photo/Video</p>
        <div class="image"><%=image_tag("Vector (6).png") %></div>
        <p> Feeling</p>
        <div class="button">
          <%= form.submit "POST"%>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="header">
  <div class="logo">
    <a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %> <h1>Maze</h1></a>  </div>

  <div class="search">
    <label>
      <input type="text" placeholder="Search">
    </label>
    <div class="profile">
      <%= image_tag("Rectangle 14.png") %>
    </div>
    <div class="name">
      <%= current_user.first_name %>
      <%= current_user.last_name %>
      <div class="role">
        <% if current_user.has_role? :admin %>
          <%= current_user.roles.pluck(:name)[0] %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%if current_user.has_role? :admin %>
  <div class="bbody">
    <div class="sidebar">
      <div class="icon1">
        <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
        <a href="http://localhost:3000/">Feed</a>
      </div>
      <div class="icon2">
        <%= image_tag("Vector (11).png") %>
        <%= link_to "Profile", user_profile_path %>
      </div>
       <div class="icon3">
      <%= image_tag("1034785-200.png") %>
      <%= link_to "Manage User", user_index_path %>
    </div>
    <div class="icon4">
      <%= image_tag("download (1).png") %>
      <%= link_to "Report", user_reports_path %>
    </div>
      <div class="icon5">
        <%=image_tag("Vector (12).png") %>
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
      </div>
    </div>
  <div class="edit1">
   <%= render "form", article: @article %>
  </div>
<% else %>
  <div class="bbody">
    <div class="sidebar">
      <div class="icon1">
        <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
        <a href="http://localhost:3000/">Feed</a>
      </div>
      <div class="icon2">
        <%= image_tag("Vector (11).png") %>
        <%= link_to "Profile", user_profile_path %>
      </div>
      <div class="icon5">
        <%=image_tag("Vector (12).png") %>
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
      </div>
    </div>
  <div class="edit1">
   <%= render "form", article: @article %>
  </div>
<% end %>


</div></div>

app/views/articles/index.html.erb
<div class="header">
  <div class="logo">
<a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %> <h1>Maze</h1></a> </div>

  <div class="search">
    <label>
      <input type="text" placeholder="Search">
    </label>
    <div class="profile">
      <%= image_tag("Rectangle 14.png") %>
    </div>
    <div class="name">
      <%= current_user.first_name %>
      <%= current_user.last_name %>
      <% if current_user.has_role? :admin %>
        <div class="role">
          <%= current_user.roles.pluck("name")[0] %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%if current_user.has_role? :admin %>
  <div class="bbody">
    <div class="sidebar">
    <div class="icon1">
      <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
      <a href="http://localhost:3000/">Feed</a>
    </div>
    <div class="icon2">
      <%= image_tag("Vector (11).png") %>
      <%= link_to "Profile", user_profile_path %>
      </div>
    <div class="icon3">
      <%= image_tag("1034785-200.png") %>
      <%= link_to "Manage User", user_index_path %>
    </div>
      <div class="icon4">
      <%= image_tag("download (1).png") %>
      <%= link_to "Report", user_reports_path %>
    </div>
    <div class="icon5">
      <%= image_tag("Vector (12).png") %>
      <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
    </div>
  </div>
    <div class="body2">
      <div>
      <%= render "form", article: @article %>
    </div>
      <% @articles.each do |article| %>
        <div class="list">
          <div class="titlebox">
            <a href="http://localhost:3000/"><%= image_tag("maze_logo.svg") %></a>
            <div class="title3">
            <h2><%= article.title %></h2>
<!--            <h2><%#= link_to article.title, article %></h2>-->

            <div class="dropdown1">
            <%@article1 = article %>
            <span>...</span>
            <div class="dropdown1-content">
              <div class="edit"><%= link_to "Edit", edit_article_path(@article1) %></div>
              <div class="delete"><%= link_to "Destroy", article_path(@article1), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } %>
              </div>
            </div>

          </div>
            </div>
            <div class="status1">
              <%= time_ago_in_words(article.created_at) %>  .
              <%= article.status %>
            </div>
          </div>

          <div class="text">
            <%= link_to article.body, article %>
          </div>
          <div class="counter">
              <%= article.likes.count %> likes.
              <%= article.comments.length %> comments
          </div>
          <hr>
          <div class="post1">
            <% like = current_user.likes.find_by(article_id: article.id) %>
            <% if like.present? %>
              <div class="unlike_button" >
                <%= button_to "","/articles/#{article.id}/likes/#{like.id}", method: :delete %>
                <p class="p"> UnLike</p>
              </div>
            <% else %>
              <div class="like_button">
                <%= button_to "", "/articles/#{article.id}/likes", method: :post %>
                <p class="p"> Like</p>
              </div>
            <% end %>
            <p class="p">
            <%=image_tag("Vector (9).png") %>
            <%= link_to "Comments", article_url(article.id) %></p>
          </div>
          <hr>
          <% @blog= article %>
          <%= render 'comments/form' %>
          <div class="ctitle">
            <% if article.comments.first&.commenter.present? %>
              <%= image_tag("maze_logo.svg") %>
              <h3><%= article.comments.order('created_at DESC').first&.commenter %></h3>
            <%end %>
          </div>
          <div class="text4">
            <%= article.comments.order('created_at DESC').first&.body %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="sidebody2">
      <div class="userlist">
        <h3>User List</h3>
        <% @user.each do |users| %>
            <% if users.articles.present? %>
              <div class="usericon">
              <%=image_tag("maze_logo.svg") %>
                <div class="user1">
              <%= users.first_name %>
              <%= users.last_name %>
                </div>
              </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="bbody">
    <div class="sidebar">
        <div class="icon1">
          <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
          <a href="http://localhost:3000/">Feed</a>
        </div>
        <div class="icon2">
          <%= image_tag("Vector (11).png") %>
          <%= link_to "Profile", user_profile_path %>
        </div>
        <div class="icon5">
          <%= image_tag("Vector (12).png") %>
          <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
        </div>
      </div>
    <div class="body">
      <div>
        <%= render "form", article: @article %>
      </div>
      <% @articles.each do |article| %>
          <div class="list">
            <div class="title5">
              <a href="http://localhost:3000/"><%= image_tag("maze_logo.svg") %></a>
              <h2><%= article.title %></h2>
<!--             <h2><%#= link_to article.title, article %></h2>-->
              <div class="dropdown">
                <%@article1 = article %>
                <span>...</span>
                <div class="dropdown-content">
                  <div class="edit"><%= link_to "Edit", edit_article_path(@article1) %></div>
                  <div class="delete"><%= link_to "Destroy", article_path(@article1), data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?"
                              } %>
                  </div>
                </div>
              </div>
              <div class="status3">
                <%= time_ago_in_words(article.created_at) %>  .
                <%= article.status %>
            </div>
            </div>
            <div class="text">
              <%= link_to article.body, article %>
            </div>
            <div class="counter">
              <%= article.likes.count %> likes.
              <%= article.comments.length %> comments
            </div>
            <hr>
            <div class="post1">
              <% like = current_user.likes.find_by(article_id: article.id) %>
              <% if like.present? %>
                <div class="unlike_button" >
                  <%= button_to "","/articles/#{article.id}/likes/#{like.id}", method: :delete %>
                  <p class="p"> UnLike</p>
                </div>
              <% else %>
                <div class="like_button">
                  <%= button_to "", "/articles/#{article.id}/likes", method: :post %>
                  <p class="p"> Like</p>
                </div>
              <% end %>
               <p class="p">
              <%=image_tag("Vector (9).png") %>
              Comment</p>
            </div>
            <hr>
            <% @blog= article %>
            <%= render 'comments/form' %>
            <div class="ctitle">
              <% if article.comments.first&.commenter.present? %>
                <%= image_tag("maze_logo.svg") %>
                <h3><%= article.comments.order('created_at DESC').first&.commenter %></h3>
              <%end %>
            </div>
            <div class="text4">
              <%= article.comments.order('created_at DESC').first&.body %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<%#= render "form", article: @article %>

app/views/articles/readme.html.erb
tanmay

app/views/articles/show.html.erb
<div class="header">
  <div class="logo">
    <a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %><h1>Maze</h1></a>  </div>
  <div class="search">
    <label>
      <input type="text" placeholder="Search">
    </label>
    <div class="profile">
      <%= image_tag("Rectangle 14.png") %>
    </div>
    <div class="name">
      <%= current_user.first_name %>
      <%= current_user.last_name %>
      <div class="role">
        <%if current_user.has_role? :admin %>
          <%= current_user.roles.pluck(:name)[0] %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%if current_user.has_role? :admin %>
    <div class="bbody">
    <div class="sidebar">
      <div class="icon1">
        <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
        <a href="http://localhost:3000/">Feed</a>
      </div>
      <div class="icon2">
        <%= image_tag("Vector (11).png") %>
        <%= link_to "Profile", user_profile_path %>
      </div>
      <div class="icon3">
        <%= image_tag("1034785-200.png") %>
        <%= link_to "Manage User", user_index_path %>
     </div>
      <div class="icon4">
      <%= image_tag("download (1).png") %>
      <%= link_to "Report", user_reports_path %>
    </div>
      <div class="icon5">
        <%=image_tag("Vector (12).png") %>
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
      </div>
    </div>
    <div class="body">
      <div class="form">
        <div class="showtitle">
          <a href="http://localhost:3000/"><%= image_tag("maze_logo.svg") %></a>
          <h2><%= @article.title %></h2>
          <div class="dropdown">
            <span>...</span>
            <div class="dropdown-content">
              <div class="edit"><%= link_to "Edit", edit_article_path(@article) %></div>
              <div class="delete"><%= link_to "Destroy", article_path(@article), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } %>
              </div>
            </div>
          </div>
          <div class="status2">
            <%= time_ago_in_words(@article.created_at) %>  .
            <%= @article.status %>
          </div>
        </div>
        <p class="text"><%= @article.body %></p>

        <div class="counter">
          <%= @article.likes.count %> likes.
          <%= @article.comments.count %> comments
        </div>
        <hr>
        <div class="post1">
          <% like = current_user.likes.find_by(article_id: @article.id) %>
          <% if like.present? %>
            <div class="unlike_button" >
              <%= button_to "","/articles/#{@article.id}/likes/#{like.id}", method: :delete %>
              <p class="p"> UnLike</p>
            </div>
          <% else %>
            <div class="like_button">
              <%= button_to "", "/articles/#{@article.id}/likes", method: :post %>
              <p class="p"> Like</p>
            </div>
          <% end %>
          <p class="p">
          <%=image_tag("Vector (9).png") %>
          Comment</p>
        </div>
        <hr>
        <%#= render 'comments/form' %>
        <%= form_with model: [ @blog, @blog.comments.build ] do |form| %>
      <p class="title1">
  <!--    <%#= form.label :commenter %><br>-->
       <%= form.text_field :commenter , value: current_user.first_name, type: :hidden, placeholder: "Title"%>
      </p>
      <div class="comment">
        <p class="body4">
  <!--    <%#= form.label :body %><br>-->
          <%= form.text_area :body ,placeholder:"Write a comment"%>
        </p>
        <p class="button1">
          <%= form.submit ""%>
        </p>
      </div>
  <!--<p class="status">-->
  <!--  <%#= form.label :status %><br>-->
    <%#= form.select :status, ['public', 'private'], selected: 'public' %>
  <!--</p>-->
    <% end %>
        <div class="comments">
          <h3>Comments</h3>
          <hr class="line">
          <%= render @article.comments.reverse %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="bbody">
    <div class="sidebar">
      <div class="icon1">
        <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
        <a href="http://localhost:3000/">Feed</a>
      </div>
      <div class="icon2">
        <%= image_tag("Vector (11).png") %>
        <%= link_to "Profile", user_profile_path %>
      </div>
      <div class="icon5">
        <%=image_tag("Vector (12).png") %>
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
      </div>
    </div>
    <div class="body">
      <div class="form">
        <div class="showtitle">
          <a href="http://localhost:3000/"><%= image_tag("maze_logo.svg") %></a>
          <h2><%= @article.title %></h2>
          <div class="dropdown">
            <span>...</span>
            <div class="dropdown-content">
              <div class="edit"><%= link_to "Edit", edit_article_path(@article) %></div>
              <div class="delete"><%= link_to "Destroy", article_path(@article), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } %>
              </div>
            </div>
          </div>
          <div class="status2">
            <%= time_ago_in_words(@article.created_at) %>  .
            <%= @article.status %>
          </div>
        </div>
        <p class="text"><%= @article.body %></p>

        <div class="counter">
          <%= @article.likes.count %> likes.
          <%= @article.comments.count %> comments
        </div>
        <hr>
        <div class="post1">
          <% like = current_user.likes.find_by(article_id: @article.id) %>
          <% if like.present? %>
            <div class="unlike_button" >
              <%= button_to "","/articles/#{@article.id}/likes/#{like.id}", method: :delete %>
              <p class="p"> UnLike</p>
            </div>
          <% else %>
            <div class="like_button">
              <%= button_to "", "/articles/#{@article.id}/likes", method: :post %>
              <p class="p"> Like</p>
            </div>
          <% end %>
          <p class="p">
          <%=image_tag("Vector (9).png") %>
          Comment</p>
        </div>
        <hr>
        <%#= render 'comments/form' %>
        <%= form_with model: [ @blog, @blog.comments.build ] do |form| %>
      <p class="title1">
  <!--    <%#= form.label :commenter %><br>-->
       <%= form.text_field :commenter , value: current_user.first_name, type: :hidden, placeholder: "Title"%>
      </p>
      <div class="comment">
        <p class="body4">
  <!--    <%#= form.label :body %><br>-->
          <%= form.text_area :body ,placeholder:"Write a comment"%>
        </p>
        <p class="button1">
          <%= form.submit ""%>
        </p>
      </div>
  <!--<p class="status">-->
  <!--  <%#= form.label :status %><br>-->
    <%#= form.select :status, ['public', 'private'], selected: 'public' %>
  <!--</p>-->
    <% end %>
        <div class="comments">
          <h3>Comments</h3>
          <hr class="line">
          <%= render @article.comments.reverse %>
        </div>
      </div>
    </div>
  </div>
<% end %>