config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  #   # Redirests signing out users back to sign-in
  #   get "users", to: "devise/sessions#new"
  # end
  devise_for :users
  root "articles#index"
     resources :articles do
    resources :comments

    resources :likes, only: [:create, :destroy]
  end
  get '/user_report', to: 'user#report'#page where csv file is downloaded
  get '/sorted_user_report', to: 'user#sorted_report'
  get '/user_reports', to: 'user#reports'#report page
  get '/article_report', to: 'articles#report'
  resources :user
  get "users/deactivate/:id" ,as:"deactivate" , to: "user#deactivate"
  get '/user_profile', to: 'user#profile'
  get '/import', to: 'user#import'
  post '/import_users', to: 'user#import_users' do
    collection {post :import}
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable
  has_many :likes, dependent: :destroy
  has_many :articles,dependent: :destroy
  has_many :comments,dependent: :destroy
  validates :first_name, presence: true, length: {maximum: 35}
  validates :last_name, presence: true, length: {maximum: 35}
  validates :phone_number, presence: true, uniqueness: true,
            format: {with: /\A[5-9][0-9]{9}\z/}
  validates :email, presence: true, uniqueness: true
  validates :password,
            format: { with: /\A(?=.*\d)(?=.*[A-z])(?=.*\W)[^ ]{8,}\z/}

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end

  require 'csv'
  def self.to_csv(options = {})
    CSV.generate( headers:true) do |csv|
      headers = ['Name', 'Posts', "Comments" ,"Likes"]
      CSV.generate_line headers
      csv << headers
      all.each do |user|
          csv << [name="#{user["first_name"]} #{user["last_name"]}",user.articles.length,user.comments.length,user.likes.length]
      end
    end
  end
  def self.to_csv2(options = {})
    CSV.generate( headers:true) do |csv|
      headers = ['Name', 'Posts', "Comments" ,"Likes"]
      CSV.generate_line headers
      csv << headers
      all.each do |user|
        if user.articles.length>10
          csv << [name="#{user["first_name"]} #{user["last_name"]}",user.articles.length,user.comments.length,user.likes.length]
        end
      end
    end
  end

   # def self.import(file)
   #      CSV.foreach(file, headers: true) do |row|
   #        User.create! row.to_hash
   #      end
   # end

  def self.import(row)
    accessible_attributes = %w[first_name last_name phone_number email password]
    user = find_by_id(row['id']) || new
    user.attributes = row.slice(*accessible_attributes)
     # user.skip_confirmation!
    user.save!
    user.add_role :user
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  # include ImportFileJob
   def index
     @users = User.all
   end

   def new
     @users = User.new
   end

   def create
     @users= User.new(user_params)
     @users.add_role params[:roles]
     @users.save
     if @users.save!
       # UserNotifierMailer.send_signup_email.deliver_now
       redirect_to user_index_path
       flash[:alert] = "This User was saved successfully"
     else
       @users.errors.full_messages
     end
   end

  def deactivate
     @users= User.find(params[:id])
     if @users.access_locked?
       @users.unlock_access!
       flash[:alert] = " ID Sucessfully Activated"
     else
       @users.lock_access!
       flash[:alert] = " ID Sucessfully Deactivated"
     end
     redirect_to user_index_path
  end

  def report
    @users = User.all
     respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv }
      format.xlsx
     end
  end

  def sorted_report
    @users = User.all
    respond_to do |format|
       format.html
       format.csv { send_data @users.to_csv2 }
       format.xlsx
     end
  end

  def profile
    @users=current_user
  end

  def edit
    @users=User.find(params[:id])
  end

   def update
    @users = User.find(params[:id])

    if @users.update(user_params)
      redirect_to @users
    else
      render :edit, status: :unprocessable_entity
    end
  end

   def import_users
     # User.import(params[:file])
     ImportFileJob.perform_now(params[:file])
     redirect_to user_index_path
   end

   # def import_users
   #  skip = true
   #
   #  CSV.foreach(params[:file].path, headers: false) do |row|
   #    unless skip
   #      accessible_attributes = %w[first_name last_name phone_number email password]
   #      hash = Hash[accessible_attributes.zip(row)]
   #      ImportFileJob.perform_now(hash)
   #    end
   #    skip = false
   #  end
   #  redirect_to user_index_path
   # end


   private
   def user_params
     params.permit(:first_name, :last_name, :phone_number, :email, :password, :password_confirmation, :role )
   end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<div class="header">
  <div class="logo">
    <a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %> <h1>Maze</h1></a>
  </div>
  <h1 class="usermanagement">User Management</h1>
  <div class="profile1">
    <%= image_tag("Rectangle 14.png") %>
  </div>
  <div class="name1">
    <%= current_user.first_name %>
    <%= current_user.last_name %>
    <div class="role">
      <%= current_user.roles.pluck("name")[0] %>
    </div>
  </div>
</div>
<div class="managementbody">
  <% if current_user.has_role? :admin %>
    <div class="sidebar">
      <div class="icon1">
        <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
        <a href="http://localhost:3000/">Feed</a>
      </div>
      <div class="icon2">
        <%= image_tag("Vector (11).png") %>
        <%= link_to "Profile", user_profile_path %>
      </div>
      <div class="icon3">
        <%= image_tag("1034785-200.png") %>
        <%= link_to "Manage User", user_index_path %>
      </div>
        <div class="icon4">
        <%= image_tag("download (1).png") %>
        <%= link_to "Report", user_reports_path %>
      </div>
      <div class="icon5">
        <%= image_tag("Vector (12).png") %>
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
      </div>
    </div>
      <%else %>
          <div class="sidebar">
        <div class="icon1">
          <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
          <a href="http://localhost:3000/">Feed</a>
        </div>
        <div class="icon2">
          <%= image_tag("Vector (11).png") %>
          <%= link_to "Profile", user_profile_path %>
        </div>
        <div class="icon5">
          <%= image_tag("Vector (12).png") %>
          <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
        </div>
      </div>
<%end %>
<div class="form2">
  <h2 class="text6">Edit User</h2>
<%= form_with  url: 'user_path', method: :PATCH   do |f| %>
    <% @users.errors.full_messages.each do |msg| %>
        <div><%= msg %></div>
      <% end %>
 <div class="fields">
  <div class="field2">
    <%= f.label :first_name %><br />
    <br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder: current_user.first_name, :maxlength => 35 %>
  </div>
  <div class="field2">
    <%= f.label :last_name %><br />
    <br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", placeholder: current_user.last_name, :maxlength => 35 %>
  </div>
 </div>
 <div class="fields">
  <div class="field2">
    <%= f.label :phone_number %><br />
    <br />
    <%= f.phone_field :phone_number, autofocus: true, autocomplete: "phone_number", placeholder: current_user.phone_number, :maxlength => 10 %>
  </div>

  <div class="field2">
    <%= f.label :email %><br />
    <br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: current_user.email %>
  </div>
 </div>
 <div class="fields">
  <div class="field2">
    <%#= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "password", placeholder: "Password", value:current_user.password ,type: :hidden%>
  </div>

  <div class="field2">
    <%#= f.label :password_confirmation %>
    <br />
    <%= f.password_field :password_confirmation, autocomplete: "password_confirmation", placeholder: "Confirm Password", value:current_user.password_confirmation ,type: :hidden %>
  </div>
 </div>
<!--    <h3 class="text7"> Assign Role</h3>-->
<!--    <div class="gap">-->
<!--      <div class="button6">-->
        <%#= f.label :user %>
        <%#= f.radio_button :roles, "user" , type: :radio %>
<!--      </div>-->
<!--      <div class="button6">-->
        <%#= f.label :user1 %>
        <%#= f.radio_button :roles, "user1" , type: :radio %>
<!--      </div>-->
<!--      <div class="button6">-->
        <%#= f.label :user2 %>
        <%#= f.radio_button :roles, "user2" , type: :radio %>
<!--      </div>-->
<!--    </div>-->

  <div class="button7">
    <%= f.submit  "Edit user" %>
  </div>
<% end %>
</div>
</div>

app/views/user/import.html.erb
<div class="header">
  <div class="logo">
    <a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %> <h1>Maze</h1></a>
  </div>
  <h1 class="usermanagement">User Management</h1>
  <div class="profile1">
    <%= image_tag("Rectangle 14.png") %>
  </div>
  <div class="name1">
    <%= current_user.first_name %>
    <%= current_user.last_name %>
    <div class="role">
     <%= current_user.roles.pluck("name")[0] %>
    </div>
  </div>
</div>
<div class="managementbody">
  <div class="sidebar">
    <div class="icon1">
      <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
      <a href="http://localhost:3000/">Feed</a>
    </div>
    <div class="icon2">
      <%= image_tag("Vector (11).png") %>
      <%= link_to "Profile", user_profile_path %>
    </div>
    <div class="icon3">
      <%= image_tag("1034785-200.png") %>
      <%= link_to "Manage User", user_index_path %>
    </div>
    <div class="icon4">
      <%= image_tag("download (1).png") %>
      <%= link_to "Report", user_reports_path %>
    </div>
    <div class="icon5">
      <%= image_tag("Vector (12).png") %>
      <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
    </div>
  </div>
  <div class="body7">
    <div class="box6">
      <p> Upload File</p>
      <div class="box7">
        <div>
          <%#= image_tag("Vector (21).png") %>
          <%= form_tag import_users_path ,multipart: true do%>
            <div class="box8">
            <%= file_field_tag :file %>
            </div>
            <div class="box9">
            <%= submit_tag " Upload File" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/index.html.erb
<div class="header">
  <div class="logo">
    <a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %> <h1>Maze</h1></a>
  </div>
  <h1 class="usermanagement">User Management</h1>
  <div class="profile1">
    <%= image_tag("Rectangle 14.png") %>
  </div>
  <div class="name1">
    <%= current_user.first_name %>
    <%= current_user.last_name %>
    <div class="role">
     <%= current_user.roles.pluck("name")[0] %>
    </div>
  </div>
</div>
<div class="managementbody">
  <div class="sidebar">
    <div class="icon1">
      <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
      <a href="http://localhost:3000/">Feed</a>
    </div>
    <div class="icon2">
      <%= image_tag("Vector (11).png") %>
      <%= link_to "Profile", user_profile_path %>
    </div>
    <div class="icon3">
      <%= image_tag("1034785-200.png") %>
      <%= link_to "Manage User", user_index_path %>
    </div>
    <div class="icon4">
      <%= image_tag("download (1).png") %>
      <%= link_to "Report", user_reports_path %>
    </div>
    <div class="icon5">
      <%= image_tag("Vector (12).png") %>
      <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
    </div>
  </div>
  <div class="container">
    <div class="title4">
      <h2>List of Users</h2>
      <div class="button8">
        <button><%= link_to "Upload Users", import_path %></button>
      </div>
      <div class="button3">
        <button><%= link_to "Create User", new_user_path %></button>
      </div>

    </div>
    <% @users.each do |users| %>
      <% if users.id!= 1 %>
        <div class="usericon1">
          <div class="logo1">
            <%=image_tag("maze_logo.svg") %>
          </div>
          <% if users.access_locked? %>
            <div class="dot1">
              <h2>.</h2>
            </div>
          <% else %>
            <div class="dot2">
              <h2>.</h2>
            </div>
          <% end %>
          <div class="name2">
            <%= users.first_name %>
            <%= users.last_name %>
          </div>
          <div class="phone">
            <%= users.phone_number %>
          </div>
          <div class="email">
            <%= users.email %>
          </div>
          <% if users.access_locked? %>
            <div class="button4">
              <button> <%= link_to 'Activate', deactivate_path(users), method: :get %></button>
              <%#= flash[:alert] = " ID Sucessfully Activated" %>
            </div>
          <% else %>
            <div class="button5">
              <button><%= link_to 'Deactivate', deactivate_path(users), method: :get %></button>
              <%#= flash[:alert] = " ID Sucessfully Deactivated" %>
            </div>
          <% end %>
              <%#= users.roles.pluck("name")[0] %>
          <h3 class="dots">...</h3>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/user/new.html.erb
<div class="header">
  <div class="logo">
    <a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %> <h1>Maze</h1></a>
  </div>
  <h1 class="usermanagement">User Management</h1>
  <div class="profile1">
    <%= image_tag("Rectangle 14.png") %>
  </div>
  <div class="name1">
    <%= current_user.first_name %>
    <%= current_user.last_name %>
    <div class="role">
      <%= current_user.roles.pluck("name")[0] %>
    </div>
  </div>
</div>
<div class="managementbody">
  <div class="sidebar">
    <div class="icon1">
      <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
      <a href="http://localhost:3000/">Feed</a>
    </div>
    <div class="icon2">
      <%= image_tag("Vector (11).png") %>
      <%= link_to "Profile", user_profile_path %>
    </div>
    <div class="icon3">
      <%= image_tag("1034785-200.png") %>
      <%= link_to "Manage User", user_index_path %>
    </div>
    <div class="icon4">
      <%= image_tag("download (1).png") %>
      <%= link_to "Report", user_reports_path %>
    </div>
    <div class="icon5">
      <%= image_tag("Vector (12).png") %>
      <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
    </div>
  </div>
<div class="form2">
  <h2 class="text6">Add User</h2>
<%= form_with  url: '/user', method: :POST   do |f| %>
    <% @users.errors.full_messages.each do |msg| %>
        <div><%= msg %></div>
      <% end %>
 <div class="fields">
  <div class="field2">
<!--    <%#= f.label :first_name %><br />-->
    <br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder: "First Name", :maxlength => 35 %>
  </div>
  <div class="field2">
<!--    <%#= f.label :last_name %><br />-->
    <br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", placeholder: "Last Name", :maxlength => 35 %>
  </div>
 </div>
 <div class="fields">
  <div class="field2">
<!--    <%#= f.label :phone_number %><br />-->
    <br />
    <%= f.phone_field :phone_number, autofocus: true, autocomplete: "phone_number", placeholder: "Phone No.", :maxlength => 10 %>
  </div>

  <div class="field2">
    <%#= f.label :email %>
    <br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email" %>
  </div>
 </div>
 <div class="fields">
  <div class="field2">
    <%#= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "password", placeholder: "Password" %>
  </div>

  <div class="field2">
    <%#= f.label :password_confirmation %>
    <br />
    <%= f.password_field :password_confirmation, autocomplete: "password_confirmation", placeholder: "Confirm Password" %>
  </div>
 </div>
    <h3 class="text7"> Assign Role</h3>
    <div class="gap">
      <div class="button6">
        <%= f.label :user %>
        <%= f.radio_button :roles, "user" , type: :radio %>
      </div>
      <div class="button6">
        <%= f.label :user1 %>
        <%= f.radio_button :roles, "user1" , type: :radio %>
      </div>
      <div class="button6">
        <%= f.label :user2 %>
        <%= f.radio_button :roles, "user2" , type: :radio %>
      </div>
    </div>

  <div class="button7">
    <%= f.submit  "Create user" %>
  </div>
<% end %>
</div>
</div>

app/views/user/profile.html.erb
<div class="header">
  <div class="logo">
<a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %> <h1>Maze</h1></a> </div>

  <div class="search">
    <label>
      <input type="text" placeholder="Search">
    </label>
    <div class="profile">
      <%= image_tag("Rectangle 14.png") %>
    </div>
    <div class="name">
      <%= current_user.first_name %>
      <%= current_user.last_name %>
      <% if current_user.has_role? :admin %>
        <div class="role">
          <%= current_user.roles.pluck("name")[0] %>
        </div>
      <% end %>
    </div>
  </div>
</div>
  <div class="bbody">
    <% if current_user.has_role? :admin %>
    <div class="sidebar">
      <div class="icon1">
        <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
        <a href="http://localhost:3000/">Feed</a>
      </div>
      <div class="icon2">
        <%= image_tag("Vector (11).png") %>
        <%= link_to "Profile", user_profile_path %>
      </div>
      <div class="icon3">
        <%= image_tag("1034785-200.png") %>
        <%= link_to "Manage User", user_index_path %>
      </div>
        <div class="icon4">
        <%= image_tag("download (1).png") %>
        <%= link_to "Report", user_reports_path %>
      </div>
      <div class="icon5">
        <%= image_tag("Vector (12).png") %>
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
      </div>
    </div>
      <%else %>
          <div class="sidebar">
        <div class="icon1">
          <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
          <a href="http://localhost:3000/">Feed</a>
        </div>
        <div class="icon2">
          <%= image_tag("Vector (11).png") %>
          <%= link_to "Profile", user_profile_path %>
        </div>
        <div class="icon5">
          <%= image_tag("Vector (12).png") %>
          <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
        </div>
      </div>
<%end %>
    <div class="body6">
      <div class="image2">
      <%= image_tag("Rectangle 14.png") %>
        <%#=link_to "Edit" , edit_user_registration_path %>
        </div>
      <div class="field3">
        <h6>Role</h6>
      <p><%= current_user.roles.pluck("name")[0] %></p>
      </div>
      <div class="field3">
        <h6>First Name</h6>
      <p><%= current_user.first_name %></p>
      </div>
      <div class="field3">
        <h6>Last Name</h6>
        <p><%= current_user.last_name %></p>
      </div>
      <div class="field3">
        <h6>Phone Number</h6>
       <p> <%= current_user.phone_number %></p>
      </div>
      <div class="field3">
        <h6>Email</h6>
        <p><%= current_user.email %></p>
      </div>
    </div>
  </div>

app/views/user/reports.html.erb
<div class="header">
  <div class="logo">
<a href="http://localhost:3000/"> <%= image_tag("maze_logo.svg") %> <h1>Maze</h1></a> </div>

  <div class="search">
    <label>
      <input type="text" placeholder="Search">
    </label>
    <div class="profile">
      <%= image_tag("Rectangle 14.png") %>
    </div>
    <div class="name">
      <%= current_user.first_name %>
      <%= current_user.last_name %>
      <% if current_user.has_role? :admin %>
        <div class="role">
          <%= current_user.roles.pluck("name")[0] %>
        </div>
      <% end %>
    </div>
  </div>
</div>
  <div class="bbody">
    <div class="sidebar">
    <div class="icon1">
      <a href="http://localhost:3000/"> <%= image_tag("images.png") %></a>
      <a href="http://localhost:3000/">Feed</a>
    </div>
    <div class="icon2">
      <%= image_tag("Vector (11).png") %>
      <%= link_to "Profile", user_profile_path %>
    </div>
    <div class="icon3">
      <%= image_tag("1034785-200.png") %>
      <%= link_to "Manage User", user_index_path %>
    </div>
      <div class="icon4">
      <%= image_tag("download (1).png") %>
      <%= link_to "Report", user_reports_path %>
    </div>
    <div class="icon5">
      <%= image_tag("Vector (12).png") %>
      <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
    </div>
  </div>
<div class="body5">
  <div class="box4">
    <div class="circle">
      <%= image_tag("Vector (17).png") %>
    </div>
<h3 class="title6">All Users</h3>
<p class="text8">Posts,comments and likes count</p>
<form>
  <div class="radio">
    <div>
  <input type="radio" id="all_user_excel" class="all_user_excel" >
  <label for="all_user_excel">Excel</label><br>
       </div>
      <div>
  <input type="radio" id="all_user_csv" class="all_user_csv" >
  <label for="all_user_csv">CSV</label><br>
    </div>

  </div>
  <div class="submit2">
  <input type="submit" class="all_user_btn" value="Download" onclick="downloadFile()">
  </div>
</form>

<script>
    let report_csv = document.getElementById('all_user_csv');
    let report_xls = document.getElementById('all_user_excel');

    let button = document.getElementById('all_user_btn');

    button.onclick = downloadFile;

    function downloadFile()
    {
        if(report_csv.checked)
        {
            window.open('/user_report.csv');
            location.reload();
        }
        else if(report_xls.checked)
        {
            window.open("/user_report.xlsx");
            location.reload();
        }
        else
        {
            alert("Please check one of the options first.");
            location.reload();
        }
    }
</script>
  </div>
<div class="box4">
  <div class="circle">
    <%= image_tag("Vector (17).png") %>
  </div>
<h3>All Users</h3>
<p>Having more than 10 post users</p>
<form>
  <div class="radio">
    <div>
  <input type="radio" id="sorted_user_excel" class="sorted_user_excel" >
  <label for="sorted_user_excel">Excel</label><br>
    </div>
    <div>
  <input type="radio" id="sorted_user_csv" class="sorted_user_csv" >
  <label for="sorted_user_csv">CSV</label><br>
    </div>
  </div>
  <div class="submit2">
  <input type="submit" class="sorted_user_btn" value="Download" onclick="sorted_downloadFile()">
  </div>
</form>

<script>
    let sorted_csv = document.getElementById('sorted_user_csv');
    let sorted_xls = document.getElementById('sorted_user_excel');
    let sorted_button = document.getElementById('sorted_user_btn');

    sorted_button.onclick = sorted_downloadFile;

    function sorted_downloadFile()
    {
        if(sorted_csv.checked)
        {
            window.open("sorted_user_report.csv");
             location.reload();
        }
        else if(sorted_xls.checked)
        {
            window.open("sorted_user_report.xlsx");
             location.reload();
        }
        else
        {
            alert("Please check one of the options first.");
             location.reload();
        }
    }
</script>
</div>
  <div class="box5">
    <div class="circle">
      <%= image_tag("Vector (17).png") %>
    </div>
<h3>Postwise Report</h3>
<p>Title/Description,comments,likes</p>
<form>
  <div class="radio">
    <div>
  <input type="radio" id="postwise_user_excel" class="postwise_user_excel" >
  <label for="postwise_user_excel">Excel</label><br>
    </div>
    <div>
  <input type="radio" id="postwise_user_csv" class="postwise_user_csv" >
  <label for="postwise_user_csv">CSV</label><br>
    </div>
  </div>
  <div class="submit2">
  <input type="submit" class="sorted_user_btn" value="Download" onclick="postwise_downloadFile()">
  </div>
</form>

<script>
    let postwise_csv = document.getElementById('postwise_user_csv');
    let postwise_xls = document.getElementById('postwise_user_excel');

    let postwise_button = document.getElementById('postwise_user_btn');

    postwise_button.onclick = postwise_downloadFile;

    function postwise_downloadFile()
    {
        if(postwise_csv.checked)
        {
            window.open("article_report.csv");
            location.reload();
        }
        else if(postwise_xls.checked)
        {
            window.open("/article_report.xlsx");
            location.reload();
        }
        else
        {
            alert("Please check one of the options first.");
            location.reload();
        }
    }
</script>
    <%=link_to 'download' , "/user_report.xlsx" %>
  </div>
</div>
  </div>